name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  issues: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # クリーンインストールを強制
      - name: Clean install dependencies
        run: |
          # 既存のロックファイルをクリーンアップ
          rm -f package-lock.json || true
          rm -rf node_modules || true
          # NPMキャッシュをクリア
          npm cache clean --force
          # 新規インストール
          npm install

      # ビルド実行
      - name: Build with Astro
        run: npm run build
        env:
          # GitHub Actionsのデフォルトトークンを使用
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # リポジトリ情報を明示的に設定
          REPO_OWNER: "nao-amj"
          REPO_NAME: "starlight-issue-wiki"

      # ビルド結果の詳細確認 (エラー診断用)
      - name: Debug - Show directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Top level directory listing:"
          ls -la
          echo "Dist directory exists?"
          if [ -d "dist" ]; then
            echo "Yes, dist directory exists"
            echo "Dist directory content:"
            ls -la dist
          else
            echo "No, dist directory does not exist"
            mkdir -p dist
            echo "Created dist directory"
          fi

      # 基本的なindex.htmlの作成（ビルドが失敗した場合のフォールバック）
      - name: Create fallback index if needed
        run: |
          if [ ! -f "dist/index.html" ]; then
            echo "Creating fallback index.html"
            echo '<!DOCTYPE html>
            <html lang="ja">
            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Starlight Issue Wiki</title>
              <meta http-equiv="refresh" content="0;url=https://github.com/nao-amj/starlight-issue-wiki">
              <style>
                body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; }
                h1 { color: #4d1a9e; }
              </style>
            </head>
            <body>
              <h1>Starlight Issue Wiki</h1>
              <p>リダイレクト中...</p>
              <p>自動的にリダイレクトされない場合は、<a href="https://github.com/nao-amj/starlight-issue-wiki">こちら</a>をクリックしてください。</p>
            </body>
            </html>' > dist/index.html
          fi

      # 404ページの作成
      - name: Create 404 page
        run: |
          if [ ! -f "dist/404.html" ]; then
            echo "Creating 404.html page"
            cp dist/index.html dist/404.html || echo "Failed to create 404.html"
          fi

      # アーティファクトのアップロード
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
