name: Update Issues JSON

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに実行

jobs:
  update-issues-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 履歴を全て取得して競合を避ける

      # Git設定を先に行う
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # 既存の変更をリセット
          git reset --hard HEAD
          git clean -fd

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Octokit
        run: npm install @octokit/rest

      # データディレクトリの存在確認と作成
      - name: Ensure data directory exists
        run: mkdir -p src/data

      - name: Fetch Issues and Update JSON
        run: |
          node -e '
          const { Octokit } = require("@octokit/rest");
          const fs = require("fs");
          const path = require("path");

          async function run() {
            const octokit = new Octokit({
              auth: process.env.GITHUB_TOKEN
            });

            const owner = "nao-amj";
            const repo = "starlight-issue-wiki";

            console.log("Fetching issues...");
            
            // 複数ページにわたるIssueを全て取得する関数
            async function fetchAllIssues() {
              let page = 1;
              let allIssues = [];
              let hasNextPage = true;
              
              while (hasNextPage) {
                console.log(`Fetching page ${page}...`);
                const { data: issues } = await octokit.issues.listForRepo({
                  owner,
                  repo,
                  state: "all",  // 全てのissueを取得（closed含む）
                  per_page: 100,
                  page: page
                });
                
                if (issues.length === 0) {
                  hasNextPage = false;
                } else {
                  allIssues = [...allIssues, ...issues];
                  page++;
                }
              }
              
              return allIssues;
            }
            
            const issues = await fetchAllIssues();

            // プルリクエストを除外
            const filteredIssues = issues.filter(issue => !issue.pull_request);

            console.log(`Found ${filteredIssues.length} issues (excluding PRs)`);

            // 必要なプロパティだけを抽出
            const formattedIssues = filteredIssues.map(issue => ({
              number: issue.number,
              title: issue.title,
              body: issue.body || "",
              html_url: issue.html_url,
              created_at: issue.created_at,
              updated_at: issue.updated_at,
              state: issue.state,
              labels: issue.labels.map(label => ({
                name: label.name,
                color: label.color,
                description: label.description
              }))
            }));

            // JSONファイルに保存
            const filePath = path.join("src", "data", "issues.json");
            fs.writeFileSync(filePath, JSON.stringify(formattedIssues, null, 2));
            console.log(`Updated ${filePath} with ${formattedIssues.length} issues`);
          }

          run().catch(error => {
            console.error("Error updating issues:", error);
            process.exit(1);
          });
          '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          # 変更をステージング
          git add src/data/issues.json
          
          # 変更があるか確認
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # コミットして直接プッシュ (rebaseなし)
          git commit -m "Update issues.json [skip ci]" || true
          git push || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
